本と日報の両方にコメント機能を追加
zeta-77/books_app pull request #9
Opened 2020-11-14 09:54 UTC by zeta-77

日報の登録削除編集機能を追加し、本と日報の両方にコメントする機能を追加した。

2020-11-20 03:53 UTC, komagata requested changes

2020-11-20 03:53 UTC, komagata commented on app/controllers/comments_controller.rb
> +    if params[:content] != ""
```suggestion
    if params[:content]
```

で大丈夫です〜

2020-11-20 03:53 UTC, komagata commented on app/controllers/comments_controller.rb
> +      redirect_back(fallback_location: root_path)
👍

2020-11-20 03:53 UTC, komagata commented on app/controllers/comments_controller.rb
> +
```suggestion
```

2020-11-20 03:53 UTC, komagata commented on app/controllers/reports_controller.rb
> +  # GET /reports/1.json
jsonとして使うことがないのであればこのコメントは不要かもです

2020-11-20 03:53 UTC, komagata commented on app/helpers/comments_helper.rb
> +module CommentsHelper
実装がないのであれば削除しちゃってください

2020-11-20 03:53 UTC, komagata commented on app/assets/stylesheets/comments.scss
> +// You can use Sass (SCSS) here: https://sass-lang.com/
不要であれば削除してください〜

2020-11-20 03:53 UTC, komagata commented on test/fixtures/comments.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
controllerテストも含めてもし動いていないのであれば削除しちゃってください

2020-11-25 01:43 UTC, zeta-77 commented on app/controllers/comments_controller.rb
> +      redirect_back(fallback_location: root_path)
ありがとうございます。そのままでOKということですね。

2020-11-25 01:43 UTC, zeta-77 commented on app/controllers/comments_controller.rb
> +
ご指摘ありがとうございます。空白行削除しました。

2020-11-25 01:44 UTC, zeta-77 commented on app/controllers/reports_controller.rb
> +  # GET /reports/1.json
ご指摘ありがとうございます。削除しました。

2020-11-25 01:44 UTC, zeta-77 commented on app/helpers/comments_helper.rb
> +module CommentsHelper
はい。ありがとうございます。削除しました。

2020-11-25 01:44 UTC, zeta-77 commented on app/assets/stylesheets/comments.scss
> +// You can use Sass (SCSS) here: https://sass-lang.com/
削除しました。

2020-11-25 01:45 UTC, zeta-77 commented on test/fixtures/comments.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
controllerの分も含めて削除しました。

2020-11-25 06:29 UTC, komagata requested changes

2020-11-25 06:29 UTC, komagata commented on app/assets/stylesheets/reports.scss
> +// Place all the styles related to the reports controller here.
こちらも不要なので削除しちゃってください〜

2020-11-25 06:29 UTC, komagata commented on app/controllers/comments_controller.rb
> +    if params[:content] != ""
こちら修正お願いします。

2020-11-25 06:29 UTC, komagata commented on app/controllers/comments_controller.rb
> +      redirect_back(fallback_location: root_path)
はい、そうです。

2020-11-25 06:29 UTC, komagata commented on app/helpers/reports_helper.rb
> +module ReportsHelper
不要な実装のないファイルは削除してください。

2020-11-25 06:29 UTC, komagata commented on test/models/report_test.rb
> +class ReportTest < ActiveSupport::TestCase
中身のないテストなどPRに追加するファイルがどんな意味を持っているのか、不要かどうか確認してみてください〜

2020-11-26 12:25 UTC, zeta-77 commented on app/assets/stylesheets/reports.scss
> +// Place all the styles related to the reports controller here.
ご指摘ありがとうございます。削除します。

2020-11-26 12:27 UTC, zeta-77 commented on app/helpers/reports_helper.rb
> +module ReportsHelper
ご指摘ありがとうございます。削除します。

2020-11-26 13:11 UTC, komagata requested changes

2020-11-26 13:11 UTC, komagata commented on app/controllers/comments_controller.rb
> +    if params[:content] != ""
こちらの行を修正お願いします。

2020-11-26 13:11 UTC, komagata commented on test/fixtures/reports.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
このfixtureも使ってなければ削除お願いします。

他にも不要なファイルがないか調べてみてください。

2020-11-27 01:31 UTC, zeta-77 commented on test/fixtures/reports.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
ご確認ありがとうございます。
不要と思われるhealperファイルを全て削除しました。fixtureファイルは全て使わない予定なので、全て削除しました。

2020-11-27 06:18 UTC, komagata requested changes

2020-11-27 06:18 UTC, komagata commented on test/models/comment_test.rb
> +class CommentTest < ActiveSupport::TestCase
動いてないテストは不要なので削除しちゃってください

2020-11-27 09:55 UTC, zeta-77 commented on test/models/comment_test.rb
> +class CommentTest < ActiveSupport::TestCase
ご確認ありがとうございます。
実装予定のないテストファイルを全て削除しました。

2020-11-30 02:00 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-12-10 07:45 UTC, merged